import projectData from './projects.json';
export const projects = projectData;
export const studio = { name: 'Studio Bind Architects', phone: '+918072701454', displayPhone: '+91 80727 01454', email: 'bindarchitects@gmail.com', address: 'No. B/28, 2nd Cross Street, Ramapuram, Chennai 600089', founded: '2019' };
export const sources = {
  coa: 'https://www.coa.gov.in/showfile.php?lang=1&level=1&lid=152&sublinkid=302',
  council: 'https://www.coa.gov.in/',
  rules: 'https://www.cmdachennai.gov.in/TNCDBR2019.html',
  cmda: 'https://www.cmdachennai.gov.in/',
  dtcp: 'https://tcp.tn.gov.in/',
};
export const services = [
 { slug:'architecture', title:'Architecture', number:'01', intro:'A home begins with how you want to live.', text:'We bring your brief, the site and the climate into one considered design. Rooms, light, circulation and structure are developed together, with a clear route from an early idea to coordinated drawings.', image:'57e60720f7e656', details:['Site and brief study','Concept and spatial planning','Design development and material direction','Consultant coordination','Working drawings and agreed site reviews'], outcome:'A coordinated design that connects everyday life with the realities of building.', projects:["sk's-residence",'ccbm','gsmt'] },
 { slug:'interior-design', title:'Interior design', number:'02', intro:'Spaces that feel like you. And work for you.', text:'Architecture and interiors influence each other. We consider movement, furniture, storage, lighting and materials early, so the finished space feels coherent down to the smallest everyday detail.', image:'8cf5ba2b295e74', details:['Lifestyle and functional brief','Furniture and space planning','Lighting and material palette','Joinery and interior details','Specifications, quantities and vendor coordination as agreed'], outcome:'A clear set of design decisions and specifications for an interior with purpose.', projects:['duplex-home-interior','casa-grande-luxe','prabhakaran-luxury-interior'] },
 { slug:'healthcare-design', title:'Healthcare spaces', number:'03', intro:'Care starts with the space around you.', text:'A clinic needs to work for patients and the people caring for them. We plan arrival, privacy, treatment rooms and staff movement with the clinical team, then coordinate the design with the relevant specialists.', image:'614982e5e56354', details:['Patient and staff movement','Consultation and treatment-room planning','Privacy and accessibility considerations','Lighting, finishes and identity','Specialist services coordination within the agreed scope'], outcome:'A welcoming clinic planned around its actual care model. Licensing and specialist compliance remain project-specific.', projects:['delphi-clinic','vedya-speciality-clinic'] },
 { slug:'commercial-interiors', title:'Work, retail & hospitality', number:'04', intro:'Good design makes room for your business.', text:'We study the way people arrive, work, browse and spend time in your space. The design connects operational needs with a recognisable identity, from a neighbourhood café to a workplace or retail interior.', image:'4a24bd6337cefa', details:['Operations and customer-journey workshop','Space planning and zoning','Brand and material expression','Lighting and furniture coordination','Technical documentation and agreed execution support'], outcome:'A space that supports the way your business operates and the experience you want to create.', projects:['east-west','kazhinadu-cafe','srishti','flora-diamonds'] },
];
export const process = [
 {title:'Listen & understand', short:'People before plans.', body:'We discuss your routines, priorities, site, budget direction and timeline. A site study helps identify constraints before they become design assumptions.', deliverable:'Project brief + scope of engagement'},
 {title:'Explore & plan', short:'Find the right spatial idea.', body:'Layouts and concepts test relationships between rooms, daylight, privacy, movement and the surrounding context. We explain the trade-offs so you can make informed choices.', deliverable:'Concept layouts + design direction'},
 {title:'Develop & coordinate', short:'Make the decisions connect.', body:'We develop the design with structural and building-services inputs. Materials, key details and budget implications are reviewed at agreed milestones.', deliverable:'Coordinated design + material direction'},
 {title:'Detail & document', short:'Give the site clarity.', body:'Working drawings and specifications communicate the agreed design. Where included, quantities and tender comparisons help you evaluate like-for-like contractor offers.', deliverable:'Working drawings + agreed specifications'},
 {title:'Review & support', short:'Keep intent visible on site.', body:'Scheduled visits, drawing clarifications and documented changes support execution. Visit frequency, specialist involvement and the contractor’s responsibilities are agreed in writing.', deliverable:'Site observations + change records'},
 {title:'Complete & hand over', short:'Close the important details.', body:'Where included in our appointment, we help review outstanding items and coordinate relevant project documents for handover.', deliverable:'Agreed completion review + handover information'},
];
export type FAQ = {category:string; question:string; answer:string; source?:string};
export const faqs: FAQ[] = [
 {category:'Getting started',question:'When should I involve an architect?',answer:'Ideally before fixing a layout, appointing a contractor or making major site decisions. An early discussion can connect your space needs with the site, budget and approval constraints. If you are buying a plot, ask about a separate pre-purchase feasibility review.'},
 {category:'Getting started',question:'What should I bring to the first meeting?',answer:'Bring the site location, available survey or plot dimensions, existing drawings if any, a short list of needs, reference images, a budget range and an intended timeline. For construction feasibility, available ownership and approval records help identify what needs further verification. Please avoid sending sensitive identity documents through an initial enquiry.'},
 {category:'Getting started',question:'Do you work in Valasaravakkam and Coimbatore?',answer:'Our studio is in Ramapuram, Chennai, close to Valasaravakkam. You can enquire about projects across Tamil Nadu, including Coimbatore. We review the location and scope before confirming an appointment; travel, local coordination and site-visit arrangements are agreed separately. We do not list a Coimbatore branch office.'},
 {category:'Getting started',question:'Can I visit a completed project?',answer:'We respect our clients’ privacy. We can share published project material and discuss suitable references. Any site visit depends on the owner’s consent, access and the project’s current stage.'},
 {category:'Architect’s role',question:'What does an architect do beyond a floor plan?',answer:'An architect translates a brief into a coordinated spatial design: light, ventilation, movement, privacy, structure, building services, materials and details all influence each other. The appointed scope can also include consultant coordination, tender support and periodic site reviews. A written appointment defines the actual services.'},
 {category:'Architect’s role',question:'How is an architect different from a contractor?',answer:'The architect develops and coordinates the design within the agreed consultancy scope. The contractor organises labour, materials, construction methods and execution under the building contract. Structural and other specialist consultants have their own defined responsibilities. Clear appointments help everyone understand their role.'},
 {category:'Architect’s role',question:'Can I appoint my own builder?',answer:'Yes, a design consultancy can work with a separately appointed contractor. Drawing coordination, tender assistance and site-review responsibilities are set out in the appointment. If you also enquire with Bind Builds, its construction scope and commercial terms are discussed separately.'},
 {category:'Fees & budgets',question:'How are architectural and interior design fees decided?',answer:'Fees depend on the project type, complexity, scope, deliverables and level of coordination. We review your brief before issuing a proposal with services, exclusions, payment stages, revisions and site-visit arrangements. Discuss these terms before appointing the studio; an area rate alone does not describe the full service.',source:sources.coa},
 {category:'Fees & budgets',question:'Is the design fee part of the construction cost?',answer:'They are separate cost heads unless your written agreement expressly combines them. A project budget may also need allowances for consultants, surveys, statutory charges, utilities, interiors, external works, taxes and contingencies. We clarify which items are included in the appointed scope.'},
 {category:'Fees & budgets',question:'Can you guarantee the final construction cost?',answer:'A reliable budget develops as the design, quantities, specifications and contractor quotations become more detailed. Market conditions, site findings and approved changes can affect the total. We help make decisions and variations visible within our scope; a final price or guarantee depends on the relevant written construction contract.'},
 {category:'Fees & budgets',question:'How are revisions and changes handled?',answer:'The appointment sets out included design stages and revisions. Changes after an approved stage should be recorded with their fee, cost and timeline implications before implementation. This helps avoid conflicting drawings and unexpected work on site.'},
 {category:'Chennai approvals',question:'Who approves a building plan in Chennai?',answer:'The relevant planning authority and local body depend on the site’s jurisdiction, building category and applicable delegation. A Chennai Metropolitan Area site needs to be checked against CMDA planning requirements and the appropriate local-body process. The approval route should be verified for the actual survey number and proposal.',source:sources.cmda},
 {category:'Chennai approvals',question:'What are FSI, setbacks and building height?',answer:'FSI relates permissible floor area to plot area; setbacks are required clear spaces around a building. Permissible height and these controls depend on factors such as the site, road width, use and building category. The Tamil Nadu Combined Development and Building Rules, 2019 must be read with current amendments and site-specific restrictions.',source:sources.rules},
 {category:'Chennai approvals',question:'Can you tell me the number of floors from plot size alone?',answer:'No. Road width, survey location, land use, plot dimensions, building category and applicable restrictions also matter. We first need a site review and the current rules; a conceptual layout is not an approval or a statement of development entitlement.',source:sources.rules},
 {category:'Chennai approvals',question:'Are approval fees and approval timelines fixed?',answer:'They depend on the authority, proposal, charge categories, documents and any further clarification or NOC requirements. Obtain an assessment for the actual submission. An architect can coordinate the agreed submission work, but the authority determines approval and processing.',source:sources.cmda},
 {category:'Chennai approvals',question:'Is CoA registration the same as planning approval?',answer:'No. The Council of Architecture regulates architectural registration and professional conduct. Planning permission and building permits concern a particular site and proposal, and are issued through the relevant authorities. You can verify an architect’s registration through the Council.',source:sources.council},
 {category:'Design & site',question:'How do you design for Chennai’s climate?',answer:'We study orientation, neighbouring buildings, shading, openings and the way air can move through the plan. Roof treatment, material choices and landscape can also influence comfort. The design response depends on the actual site; performance claims need an appropriate calculation or assessment.'},
 {category:'Design & site',question:'Can Vastu preferences be included?',answer:'Tell us your priorities at the start. We discuss how they fit with daylight, ventilation, privacy, circulation, structure and the applicable rules. Where priorities compete, we explain the options and agree a workable direction with you.'},
 {category:'Design & site',question:'Does an architect stay on site every day?',answer:'Periodic architectural site reviews and full-time site supervision are different services. Visit frequency, reporting and personnel depend on your appointment. The contractor remains responsible for construction methods, workforce, site safety and execution under its contract.'},
 {category:'Design & site',question:'Do you take renovation and small interior projects?',answer:'You can share the existing condition, location, requirements and budget direction with us. Renovations may need a measured survey and specialist structural assessment before changes are proposed. We confirm project fit and the services available after reviewing the brief.'},
];
export const locations = [
 {slug:'architects-in-chennai',name:'Chennai',eyebrow:'Rooted in Chennai',title:'Architecture for the way Chennai lives.',description:'Architecture and interior design in Chennai, from our Ramapuram studio. Explore homes, clinics, workplaces and commercial projects by Studio Bind Architects.',intro:'A dense urban plot, a multigenerational home, a clinic with a busy daily rhythm. Every Chennai project begins with understanding both the people and the place.',points:[['Climate & comfort','Orientation, shade, natural light and air movement need to be considered together, especially on closely built sites.'],['Urban site realities','Road width, access, neighbouring buildings, parking and servicing influence a workable plan from the beginning.'],['One coordinated design','Architecture, interiors, structure and services benefit from early coordination before work moves to site.']],areas:'Ramapuram · Valasaravakkam · Porur · Anna Nagar · Maduravoyal · OMR · ECR',projectSlugs:['delphi-clinic','east-west','ccbm']},
 {slug:'architects-in-valasaravakkam',name:'Valasaravakkam',eyebrow:'A nearby design studio',title:'A considered home in Valasaravakkam.',description:'Discuss architecture and interior design for Valasaravakkam with Studio Bind Architects, based nearby in Ramapuram, Chennai.',intro:'Planning a new home or adapting an existing one in Valasaravakkam? Start with how your family lives today and how the home might need to change over time.',points:[['Make the plot work harder','We explore room proportions, usable circulation, privacy and daylight together instead of simply maximising the number of rooms.'],['Plan for generations','Access, a ground-floor bedroom, flexibility and future needs can be discussed before the layout becomes fixed.'],['Keep site decisions connected','Existing structure, drainage, service connections and the authority’s requirements need site-specific checks.']],areas:'Consultations at our Ramapuram studio by appointment. We do not list a separate Valasaravakkam office.',projectSlugs:["sk's-residence",'gsmt','duplex-home-interior']},
 {slug:'architects-in-coimbatore',name:'Coimbatore',eyebrow:'Tamil Nadu project enquiries',title:'Your Coimbatore brief. A thoughtful beginning.',description:'Enquire about architecture and interior design for a Coimbatore project with Studio Bind Architects. Scope, travel and local coordination are confirmed after review.',intro:'We welcome conversations about homes, workplaces, healthcare and commercial spaces in Coimbatore. Our studio is based in Chennai; the appointment and local support are planned around the project.',points:[['Begin with a site brief','Share the location, plot information, project type and your priorities so we can assess the appropriate design scope.'],['Agree how we collaborate','Remote workshops, in-person reviews, travel and site-visit arrangements are defined before work starts.'],['Check the local approval route','The relevant planning authority, local body and required consultants must be verified for the actual site.']],areas:'Coimbatore enquiries are reviewed individually. No Coimbatore branch or locally completed project is implied.',projectSlugs:['chettinadu-home','ttdc']},
 {slug:'architects-in-tamilnadu',name:'Tamil Nadu',eyebrow:'Architecture, with a sense of place',title:'Different places. Considered responses.',description:'Explore Studio Bind Architects’ architecture and interior design work in Tamil Nadu, with projects in Chennai, Madurai, Yercaud and Sunguvarchathiram.',intro:'The way we build should respond to the place we are building in. Across Tamil Nadu, climate, routines, craft and site conditions bring different questions to the design process.',points:[['Context before a style','A courtyard, a shaded threshold or a contemporary interior begins with what the people and the site actually need.'],['Scope that fits the location','Travel, specialist coordination and execution support are agreed project by project from our Chennai studio.'],['Evidence through work','Explore the published portfolio, including a farmhouse in Madurai, a hospitality proposal in Yercaud and a home in Sunguvarchathiram.']],areas:'Chennai-based practice · Project appointments across Tamil Nadu subject to scope and availability',projectSlugs:['chettinadu-home','ttdc',"sk's-residence"]},
];
export const articles = [
 {slug:'before-you-build-in-chennai',title:'Before you build in Chennai.',tag:'Planning a home',description:'The questions to resolve before the first drawing becomes a building.',read:'4 min read',sections:[['Start with the life inside','Write down who will use the home, what a normal weekday looks like, what needs privacy and what needs to be shared. Include storage, work, ageing parents, visitors and possible future changes. These details create a much more useful brief than a room count alone.'],['Understand the site','Collect the available survey, plot dimensions, road information and ownership and approval records. A feasibility review should check the actual site and applicable development controls. Legal title due diligence and specialist reports may require separate appointments.'],['Build a complete budget','Discuss a range for the whole project, then separate construction, interiors, professional fees, statutory charges, services, external works and contingency. Ask which items a quotation includes before comparing its area rate with another.'],['Agree the team and responsibilities','Clarify who develops the design, who provides structural and services input, who makes submissions and who executes the works. Record deliverables, payment stages and site-review arrangements in the appointment.'],['Leave time for decisions','A rushed start can move unresolved choices onto the site. Agree design reviews and decisions before procurement or construction reaches the relevant stage.']],source:sources.rules},
 {slug:'what-an-architect-actually-does',title:'The decisions behind a good space.',tag:'Working with an architect',description:'How design brings light, daily life, budgets and execution into the same conversation.',read:'3 min read',sections:[['Translate needs into relationships','Where should the kitchen sit relative to dining, utilities and the entrance? Which rooms need quiet? An architect studies these relationships and tests alternatives instead of treating each room as an isolated box.'],['Connect the visible and the invisible','Structure, plumbing, electrical services and ventilation shape the design as much as furniture and finishes do. Coordinating those inputs early makes conflicts easier to discuss before construction.'],['Make trade-offs understandable','More glazing may bring a view but also change heat gain and privacy. A different material may affect upkeep and cost. Design consultation helps you weigh choices in the context of your priorities.'],['Communicate for execution','Working drawings, specifications, consultant information and agreed site reviews communicate intent. The services you receive should always be described in a written appointment.']],source:sources.coa},
 {slug:'design-fees-and-scope',title:'Compare the scope. Understand the fee.',tag:'Fees & appointments',description:'Five things to read in an architectural proposal before you compare the price.',read:'3 min read',sections:[['What is included?','Read the stages and deliverables. Concept plans, visualisations, working drawings, consultant coordination, tender assistance and site reviews are distinct services; do not assume they are all included.'],['What is separate?','Ask about surveys, structural and services consultants, statutory charges, travel, specialist reports, taxes and additional revisions. Record exclusions as clearly as inclusions.'],['How will decisions be approved?','Agree the review process and the point at which a design stage is signed off. Changes afterwards should identify their effect on fees, construction cost and time.'],['Who will visit the site?','Understand the frequency, purpose and reporting of visits. Periodic architectural reviews do not imply a full-time site supervisor.'],['What does the appointment say?','Scope, responsibilities, fees and payment stages should be discussed and agreed in writing. Consult the Council of Architecture’s professional guidance as part of understanding the architect–client relationship.']],source:sources.coa},
];
