import Image from 'next/image';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {projects} from '@/lib/content';
import {Label,ContactCTA,TextLink,JsonLd} from '@/components/ui';
import {meta,siteUrl} from '@/lib/seo';
export function generateStaticParams(){return projects.map(p=>({slug:p.slug}))}
export const dynamicParams=false;
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(p=>p.slug===slug);return p?meta(p.name,`${p.name} by Studio Bind Architects. ${p.scope}. ${p.location}. ${p.status}.`,`/project/${encodeURIComponent(slug)}`):{title:'Project not found'}}
export default async function Project({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(p=>p.slug===slug);if(!p)notFound();const index=projects.indexOf(p);const next=projects[(index+1)%projects.length];return <><section className="wrap project-intro"><Link className="back-link" href="/works">← All projects</Link><Label>{p.sector} {p.location?`/ ${p.location}`:''}</Label><h1>{p.name}</h1><div className="project-meta">{[['Scope',p.scope],['Area',p.area],['Status',p.status]].filter(([,v])=>v).map(([k,v])=><div key={k}><span>{k}</span><p>{v}</p></div>)}</div></section><div className="project-cover"><Image src={p.images[0]} alt={`${p.name} — ${p.scope}`} fill priority sizes="100vw"/></div><section className="wrap project-story"><div><Label>The project</Label><h2>{p.status==='Proposal'?'A design exploration.':'A considered response.'}</h2></div><div>{p.description?<p>{p.description}</p>:<p>{p.name} brings together Studio Bind’s work in {p.scope.toLowerCase()}{p.location?` for a project in ${p.location}`:''}. Explore the design and project images below.</p>}<p className="project-credit"><strong>Project team</strong><br/>{p.team||'Studio Bind Architects'}</p><p className="form-hint">{p.status==='Proposal'?'Design proposal. Images show the proposed design.':p.status==='Ongoing'?'Ongoing project. The gallery may include design visualisations and progress photographs.':'Published project gallery. Refer to the listed scope for Studio Bind’s role.'}</p></div></section><section className="wrap project-gallery" aria-label={`${p.name} image gallery`}>{p.images.slice(1).map((src,i)=><figure key={src} className={i%5===0?'wide':''}><div><Image src={src} alt={`${p.name} — project gallery view ${i+2}`} fill sizes="(max-width:700px) 100vw, 70vw"/></div></figure>)}</section><div className="wrap next-project"><span className="eyebrow">Next project</span><TextLink href={`/project/${encodeURIComponent(next.slug)}`}>{next.name}</TextLink></div><ContactCTA/><JsonLd data={{'@context':'https://schema.org','@type':'CreativeWork',name:p.name,url:siteUrl+`/project/${encodeURIComponent(p.slug)}`,creator:{'@id':siteUrl+'/#studio'},description:`Studio Bind scope: ${p.scope}. Project team: ${p.team}. Status: ${p.status}.`,image:siteUrl+p.images[0]}}/></>}
