import type {Metadata} from 'next';
import localFont from 'next/font/local';
import Link from 'next/link';
import Image from 'next/image';
import {Header} from '@/components/header';
import {Experience,AnalyticsChoice} from '@/components/experience';
import {JsonLd,Arrow} from '@/components/ui';
import {studio,locations} from '@/lib/content';
import {siteUrl,indexable} from '@/lib/seo';
import './globals.css';
const sans=localFont({src:[{path:'../../public/fonts/manrope-0.woff2',weight:'400'},{path:'../../public/fonts/manrope-1.woff2',weight:'500'},{path:'../../public/fonts/manrope-2.woff2',weight:'600'},{path:'../../public/fonts/manrope-3.woff2',weight:'700'}],variable:'--font-sans',display:'swap'});
const serif=localFont({src:[{path:'../../public/fonts/serif-1.woff2',weight:'400',style:'normal'},{path:'../../public/fonts/serif-0.woff2',weight:'400',style:'italic'}],variable:'--font-serif',display:'swap'});
export const metadata:Metadata={metadataBase:new URL(siteUrl),title:{default:'Architects in Chennai | Studio Bind Architects',template:'%s | Studio Bind Architects'},description:'Studio Bind Architects is a Chennai-based architecture and interior design practice. Thoughtful homes, healthcare, workplace and commercial spaces.',robots:indexable?{index:true,follow:true}:{index:false,follow:false},openGraph:{siteName:studio.name,locale:'en_IN',type:'website'},twitter:{card:'summary_large_image'}};
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="en" className={`${sans.variable} ${serif.variable}`}><body><Header/><main id="main">{children}</main><footer className="site-footer"><div className="footer-top wrap"><div className="footer-brand"><Image src="/images/logo.png" alt="Studio Bind Architects" width={148} height={60}/><p>Thoughtful spaces.<br/>Meaningful everyday lives.</p><small>Architecture · Interiors · Chennai</small></div><div><h2>Explore</h2>{[['Selected work','/works'],['The studio','/studio'],['Our expertise','/services'],['Our process','/process'],['Why an architect?','/why-an-architect']].map(([label,href])=><Link href={href} key={href}>{label}</Link>)}</div><div><h2>Good to know</h2>{[['Client questions','/faq'],['Fieldnotes','/insights'],['Professional standards','/professional-standards'],['Privacy','/privacy']].map(([label,href])=><Link href={href} key={href}>{label}</Link>)}<a href="https://www.bindbuilds.com/" target="_blank" rel="noreferrer">Bind Builds ↗</a></div><div className="footer-contact"><h2>Let’s talk</h2><a href={`mailto:${studio.email}`}>{studio.email}<Arrow diagonal/></a><a href={`tel:${studio.phone}`}>{studio.displayPhone}</a><p>{studio.address}<br/><small>Studio visits by appointment.</small></p></div></div><div className="footer-locations wrap">{locations.map(l=><Link key={l.slug} href={`/${l.slug}`}>Architects in {l.name}<span>↗</span></Link>)}</div><div className="footer-bottom wrap"><span>© {new Date().getFullYear()} Studio Bind Architects</span><span>Designed with intention.</span><Link href="/contact">Start a conversation ↗</Link></div></footer><Experience/><AnalyticsChoice/><JsonLd data={{'@context':'https://schema.org','@type':'ProfessionalService','@id':siteUrl+'/#studio',name:studio.name,url:siteUrl,email:studio.email,telephone:studio.phone,foundingDate:'2019',image:siteUrl+'/images/logo.png',address:{'@type':'PostalAddress',streetAddress:'No. B/28, 2nd Cross Street, Ramapuram',addressLocality:'Chennai',addressRegion:'Tamil Nadu',postalCode:'600089',addressCountry:'IN'},areaServed:[{'@type':'City',name:'Chennai'},{'@type':'AdministrativeArea',name:'Tamil Nadu'}]}}/></body></html>}
