'use client';
import {useRef,useState} from 'react';
import {Arrow} from './ui';
import {studio} from '@/lib/content';
import {track} from './experience';
const initial={kind:'',location:'',budget:'',timeline:'',name:'',phone:'',email:'',notes:''};
export function ProjectBrief(){const [step,setStep]=useState(0);const [data,setData]=useState(initial);const heading=useRef<HTMLHeadingElement>(null);const [consent,setConsent]=useState(false);const [copied,setCopied]=useState(false);
 const change=(key:keyof typeof initial,value:string)=>{setData(d=>({...d,[key]:value}));setCopied(false)};
 const brief=`Hello Studio Bind Architects,\n\nI would like to discuss a project.\n\nName: ${data.name}\nPhone: ${data.phone}\n${data.email?`Email: ${data.email}\n`:''}Project: ${data.kind}\nLocation: ${data.location}\nBudget direction: ${data.budget||'To discuss'}\nTimeline: ${data.timeline||'To discuss'}\n${data.notes?`\nBrief: ${data.notes}`:''}\n\nPlease contact me about this enquiry.`;
 function next(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStep(s=>s+1);if(step===2)track('brief_prepared');requestAnimationFrame(()=>heading.current?.focus())}
 return <div className="brief-builder"><div className="brief-progress" aria-label="Enquiry progress">{['Your project','Your priorities','About you'].map((label,i)=><span key={label} className={step>=i?'active':''}><b>0{i+1}</b>{label}</span>)}</div><h2 ref={heading} tabIndex={-1}>{['What are you planning?','What matters to you?','How can we reach you?','Your brief is ready.'][step]}</h2><p className="form-hint">{step<3?'A few details help us begin a more useful conversation.':'Review the details, then choose how to share them with the studio.'}</p>{step<3?<form onSubmit={next}>
 {step===0?<><fieldset><legend>Project type</legend><div className="choice-grid">{['A new home','Home interiors','Clinic or healthcare','Workplace','Retail or hospitality','Renovation'].map(kind=><label className={data.kind===kind?'choice selected':'choice'} key={kind}><input type="radio" name="kind" value={kind} required checked={data.kind===kind} onChange={e=>change('kind',e.target.value)}/>{kind}<span aria-hidden="true">↗</span></label>)}</div></fieldset><label className="field">Where is your project?<input name="location" autoComplete="address-level2" placeholder="Area and city" required maxLength={120} value={data.location} onChange={e=>change('location',e.target.value)}/></label></>:null}
 {step===1?<><div className="form-grid"><label className="field">Overall budget direction<select value={data.budget} onChange={e=>change('budget',e.target.value)}><option value="">Let’s discuss</option>{['Below ₹15 lakh','₹15–30 lakh','₹30–60 lakh','₹60 lakh–₹1 crore','₹1–2 crore','Above ₹2 crore'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field">When would you like to begin?<select value={data.timeline} onChange={e=>change('timeline',e.target.value)}><option value="">Exploring options</option>{['Within 3 months','In 3–6 months','In 6–12 months','More than a year away'].map(v=><option key={v}>{v}</option>)}</select></label></div><label className="field">What should we know? <span>(optional)</span><textarea rows={4} placeholder="Site size, the people using the space, or your main priorities…" maxLength={1500} value={data.notes} onChange={e=>change('notes',e.target.value)}/></label><p className="form-hint">A budget range helps us understand the brief. It is not a quotation or an agreed project cost.</p></>:null}
 {step===2?<><label className="field">Your name<input name="name" autoComplete="name" required minLength={2} maxLength={100} value={data.name} onChange={e=>change('name',e.target.value)}/></label><div className="form-grid"><label className="field">Phone number<input type="tel" name="phone" autoComplete="tel" inputMode="tel" required pattern="[+0-9 ()-]{8,20}" title="Enter a phone number with 8 to 20 characters" value={data.phone} onChange={e=>change('phone',e.target.value)}/></label><label className="field">Email <span>(optional)</span><input type="email" name="email" autoComplete="email" maxLength={180} value={data.email} onChange={e=>change('email',e.target.value)}/></label></div><label className="consent-field"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I agree to share these details with Studio Bind Architects for a response to my project enquiry. <a href="/privacy">Privacy notice</a>.</span></label></>:null}
 <div className="form-actions">{step>0?<button type="button" className="back-button" onClick={()=>setStep(s=>s-1)}>← Back</button>:<span/>}<button className="button" type="submit">{step===2?'Review my brief':'Continue'}<Arrow/></button></div><p className="form-footnote">Your details stay in this page until you choose WhatsApp or email. Please do not include sensitive documents.</p></form>:<div className="brief-review"><pre>{brief}</pre><div className="form-actions"><button onClick={()=>setStep(2)} className="back-button">← Edit details</button></div><div className="share-options"><a className="button" href={`https://wa.me/${studio.phone.replace('+','')}?text=${encodeURIComponent(brief)}`} target="_blank" rel="noreferrer" onClick={()=>track('contact_whatsapp')}>Open in WhatsApp<Arrow diagonal/></a><a className="button button-outline" href={`mailto:${studio.email}?subject=${encodeURIComponent('Project enquiry — '+data.kind+' — '+data.location)}&body=${encodeURIComponent(brief)}`} onClick={()=>track('contact_email')}>Open email draft<Arrow diagonal/></a></div><p className="form-hint" role="status">This brief has not been sent. Complete the send action in WhatsApp or your email app.</p><button className="copy-button" onClick={async()=>{try{await navigator.clipboard.writeText(brief);setCopied(true)}catch{setCopied(false)}}}>{copied?'Copied to clipboard':'Copy brief'}</button></div>}</div>
}
