import Link from 'next/link';
import Image from 'next/image';
import { projects } from '@/lib/content';
export function Arrow({diagonal=false}:{diagonal?:boolean}) {return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d={diagonal?'M5 19 19 5M5 5h14v14':'M4 12h16m-6-6 6 6-6 6'} stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/></svg>}
export function ButtonLink({href,children,light=false}:{href:string;children:React.ReactNode;light?:boolean}){return <Link className={`button ${light?'button-light':''}`} href={href}>{children}<Arrow/></Link>}
export function TextLink({href,children}:{href:string;children:React.ReactNode}){return <Link className="text-link" href={href}>{children}<Arrow diagonal/></Link>}
export function Label({children}:{children:React.ReactNode}){return <p className="eyebrow"><span className="tiny-square"/>{children}</p>}
export function PageIntro({label,title,description}:{label:string;title:React.ReactNode;description:string}){return <section className="page-intro wrap"><Label>{label}</Label><h1>{title}</h1><p className="intro-description">{description}</p></section>}
export function ProjectCard({project,large=false}:{project:typeof projects[number];large?:boolean}){return <Link href={`/project/${encodeURIComponent(project.slug)}`} className={`project-card ${large?'large':''}`} data-reveal><div className="project-image"><Image src={project.images[0]} alt={`${project.name} — ${project.scope}`} fill sizes={large?'(max-width: 700px) 100vw, 65vw':'(max-width: 700px) 100vw, 50vw'}/><span className="image-tag">{project.status === 'Proposal'?'Design proposal':project.status}</span><span className="image-arrow"><Arrow diagonal/></span></div><div className="project-caption"><div><p>{project.sector} {project.location?` / ${project.location}`:''}</p><h3>{project.name}</h3></div><span className="project-number">↗</span></div></Link>}
export function ContactCTA(){return <section className="contact-cta wrap" data-reveal><div><Label>Your next chapter</Label><h2>Let’s begin with<br/><em>a conversation.</em></h2></div><div><p>Tell us about your site, your people,<br className="desktop-only"/> and what you have in mind.</p><ButtonLink href="/contact">Discuss your project</ButtonLink></div></section>}
export function JsonLd({data}:{data:object}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,'\\u003c')}}/>}
