import {chromium} from 'playwright-core';
import AxeBuilder from '@axe-core/playwright';
import {spawn} from 'node:child_process';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const base='http://127.0.0.1:3100';
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port','3100'],{cwd:process.cwd(),stdio:['ignore','pipe','pipe']});
let browser;
const report={checkedAt:new Date().toISOString(),routes:[],responsive:[],accessibility:[],journeys:[],browserErrors:[]};
try{
 await new Promise((resolve,reject)=>{server.stdout.on('data',d=>{if(d.toString().includes('Ready in'))resolve()});server.stderr.on('data',d=>process.stderr.write(d));server.on('error',reject);setTimeout(()=>reject(Error('server start timeout')),15000).unref()});
 browser=await chromium.launch({executablePath:process.env.CHROME_EXECUTABLE_PATH||undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage();page.setDefaultTimeout(15000);page.setDefaultNavigationTimeout(30000);page.on('pageerror',e=>report.browserErrors.push(e.message));
 const manifest=JSON.parse(await readFile('.next/prerender-manifest.json','utf8'));
 const routes=Object.keys(manifest.routes).filter(r=>!r.startsWith('/_')&&!r.includes('/opengraph-image')&&!r.endsWith('.txt')&&!r.endsWith('.xml')&&!r.endsWith('.svg'));
 for(const route of routes){const response=await fetch(base+route);const html=await response.text();assert.equal(response.status,200,route);assert.equal((html.match(/<h1[ >]/g)||[]).length,1,route+' one h1');assert.ok(html.includes('noindex'),route+' preview noindex');assert.ok(html.includes('rel="canonical"'),route+' canonical');for(const m of html.matchAll(/<script type="application\/ld\+json">(.*?)<\/script>/g))JSON.parse(m[1]);report.routes.push({route,status:200});}
 console.log('Routes verified:',report.routes.length);
 for(const [from,to] of [['/blank','/studio'],['/blank-2','/project/flora-diamonds'],['/projects','/works'],['/architects-in-tamil-nadu','/architects-in-tamilnadu']]){const r=await fetch(base+from,{redirect:'manual'});assert.equal(r.status,308);assert.ok(r.headers.get('location').endsWith(to));}
 assert.equal((await fetch(base+'/this-page-does-not-exist')).status,404);
 assert.ok((await (await fetch(base+'/robots.txt')).text()).includes('Disallow: /'));
 report.journeys.push('43 content routes, canonicals, JSON-LD, preview indexing protection, 308 redirects and 404 handling');
 await page.goto(base,{waitUntil:'domcontentloaded'});
 for(const width of [320,375,390,768,1024,1440,1920,2560]){await page.setViewportSize({width,height:900});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.ok(!overflow,'home overflow '+width);report.responsive.push({route:'/',width,overflow});}
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>document.fonts.ready);await page.locator('.hero-picture').evaluate(i=>i.complete?null:new Promise(r=>{i.onload=r;i.onerror=r}));await page.screenshot({path:'test-results/home-desktop.png'});
 await page.getByRole('button',{name:'Life & movement',exact:true}).click();await page.getByRole('heading',{name:'A plan follows your everyday.'}).waitFor();
 await page.getByRole('button',{name:'Details & coordination',exact:true}).click();await page.getByRole('heading',{name:'Make the decisions connect.'}).waitFor();
 await page.getByRole('button',{name:'Show Delphi Clinic',exact:true}).click();assert.ok(await page.locator('.hero-project').innerText().then(t=>t.includes('Delphi Clinic')));report.journeys.push('Manual hero project selector and interactive design layers');
 await page.setViewportSize({width:390,height:844});await page.goto(base,{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Open menu',exact:true}).click();assert.ok(await page.locator('#mobile-nav').isVisible());await page.keyboard.press('Escape');assert.ok(!await page.locator('#mobile-nav').isVisible());await page.getByRole('button',{name:'Open menu',exact:true}).click();await page.locator('#mobile-nav').getByRole('link',{name:'Work',exact:false}).first().click();await page.waitForURL('**/works');assert.ok(!await page.locator('#mobile-nav').isVisible());report.journeys.push('Mobile menu, Escape dismissal, focus return and route change');
 await page.getByRole('button',{name:'Healthcare',exact:true}).click();assert.equal(await page.locator('.project-card').count(),2);await page.getByRole('button',{name:'All',exact:true}).click();assert.equal(await page.locator('.project-card').count(),20);report.journeys.push('Project filters: 20 total, 2 healthcare');
 await page.goto(base+'/faq',{waitUntil:'domcontentloaded'});await page.getByLabel('Find an answer').fill('FSI');assert.ok(await page.locator('details').count()>0);await page.locator('summary').first().click();assert.ok(await page.locator('details').first().getAttribute('open')!==null);await page.getByLabel('Find an answer').fill('xx-no-result-xx');assert.equal(await page.locator('details').count(),0);await page.getByRole('button',{name:'Show all questions',exact:true}).click();assert.equal(await page.locator('details').count(),20);report.journeys.push('FAQ search, expanded answers and empty-state recovery');
 await page.goto(base+'/contact',{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Continue',exact:true}).click();assert.ok(await page.getByRole('heading',{name:'What are you planning?'}).isVisible());await page.getByRole('radio',{name:'A new home'}).check();await page.getByLabel('Where is your project?').fill('Valasaravakkam, Chennai');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('Overall budget direction').selectOption('₹60 lakh–₹1 crore');await page.getByLabel('When would you like to begin?').selectOption('In 3–6 months');await page.getByLabel('What should we know?').fill('TEST ONLY — courtyard and accessible ground floor');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('Your name',{exact:true}).fill('Test Client');await page.getByLabel('Phone number',{exact:true}).fill('abc');await page.getByRole('button',{name:'Review my brief'}).click();assert.ok(await page.getByRole('heading',{name:'How can we reach you?'}).isVisible());await page.getByLabel('Phone number',{exact:true}).fill('9000000000');await page.getByLabel('Email (optional)').fill('test@example.com');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Review my brief'}).click();await page.getByRole('heading',{name:'Your brief is ready.'}).waitFor();const wa=await page.getByRole('link',{name:'Open in WhatsApp'}).getAttribute('href');const mail=await page.getByRole('link',{name:'Open email draft'}).getAttribute('href');assert.equal(new URL(wa).host,'wa.me');assert.ok(new URL(wa).searchParams.get('text').includes('Valasaravakkam'));assert.ok(mail.startsWith('mailto:bindarchitects@gmail.com'));assert.ok(await page.getByRole('status').innerText().then(t=>t.includes('has not been sent')));await page.getByRole('button',{name:'Edit details'}).click();assert.equal(await page.getByLabel('Your name',{exact:true}).inputValue(),'Test Client');report.journeys.push('Brief validation, 3 stages, edit persistence, correct WhatsApp/email drafts; no enquiry sent');
 for(const route of ['/','/works','/faq','/contact','/services/architecture','/project/duplex-home-interior','/architects-in-coimbatore','/professional-standards']){await page.goto(base+route,{waitUntil:'domcontentloaded'});const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();report.accessibility.push({route,violations:audit.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))});for(const width of [320,768,1440]){await page.setViewportSize({width,height:900});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);report.responsive.push({route,width,overflow});assert.ok(!overflow,route+' overflow '+width);}}
 console.log('Accessibility findings:',JSON.stringify(report.accessibility.filter(a=>a.violations.length)));
 await page.setViewportSize({width:1440,height:1000});await page.goto(base,{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.fonts.ready);await page.locator('.hero-picture').evaluate(i=>i.complete?null:new Promise(r=>{i.onload=r;i.onerror=r}));await page.screenshot({path:'test-results/home-desktop.png'});await page.emulateMedia({reducedMotion:'reduce'});await page.screenshot({path:'test-results/home-full.png',fullPage:true});assert.equal(await page.locator('.hero-picture').evaluate(el=>getComputedStyle(el).animationName),'none');report.journeys.push('Reduced-motion support');
 await page.setViewportSize({width:390,height:844});await page.goto(base,{waitUntil:'domcontentloaded'});await page.screenshot({path:'test-results/home-mobile.png'});await page.goto(base+'/contact',{waitUntil:'domcontentloaded'});await page.screenshot({path:'test-results/contact-mobile.png',fullPage:true});await page.goto(base+'/faq',{waitUntil:'domcontentloaded'});await page.screenshot({path:'test-results/faq-mobile.png',fullPage:true});
 assert.equal(report.browserErrors.length,0,'Browser runtime errors');
 if(report.accessibility.some(a=>a.violations.length))process.exitCode=1;
 console.log(JSON.stringify({routes:report.routes.length,responsive:report.responsive.length,journeys:report.journeys.length,accessibilityPages:report.accessibility.length,browserErrors:report.browserErrors}));
} catch(e){report.failure=e.stack;console.error(e);process.exitCode=1} finally {await mkdir('test-results',{recursive:true});await writeFile('test-results/verification.json',JSON.stringify(report,null,2));await browser?.close();server.kill()}
